name: CI

on:
  push:
    branches:
      - "master"
  pull_request:

concurrency:
  group: "${{ github.head_ref || format('{0}-{1}', github.run_number, github.run_attempt) }}"

jobs:
  coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - 3.9

    steps:
      - name: "Show me some things"
        run: |
          echo '${{ toJSON(github) }}'

      - name: "Show candidate concurrency group"
        run: |
          echo ${{ github.head_ref || format('{0}-{1}', github.run_number, github.run_attempt) }}

      - name: "Be slow"
        run: |
          sleep 60
